### ISSUE TITLE
数据预处理问题

### ISSUE THREAD

**Issue by LiangYong1216** [FreedomIntelligence/HuatuoGPT-II#19]
我使用了你们开元的50000条的数据集，当使用data_process.py进行数据处理时，报错了：
The dataset will save in HuatuoGPT2_sft_instruct_GPT4_HuatuoGPT2-7B_4096_dataset
Traceback (most recent call last):
  File "/home/ly/test/HuatuoGPT-II-main/adaption/one_stage_training/data_process.py", line 274, in <module>
    preprocess(args)
  File "/home/ly/test/HuatuoGPT-II-main/adaption/one_stage_training/data_process.py", line 201, in preprocess
    train_dataset = HuatuoGPT_data(args, tokenizer)
  File "/home/ly/test/HuatuoGPT-II-main/adaption/one_stage_training/data_process.py", line 90, in __init__
    self.data_dict = json.load(f)
  File "/home/ly/anaconda3/envs/huatuo/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/ly/anaconda3/envs/huatuo/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/ly/anaconda3/envs/huatuo/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 598)

Process finished with exit code 1
数据集长这样：
![image](https://github.com/FreedomIntelligence/HuatuoGPT-II/assets/66230782/02220bc8-e63d-4809-8e70-56400f6e3f1e)
应该如何修改数据集格式？或者修改某处代码？

**Comment by qlibp** [comment]
手动改，改成形如下的json文件
```
{
    "SFT_data": [
     ["问：xxxxx",
      "答：xxxxx"]
    ]
}
```

**Comment by jymChen** [comment]
> 手动改，改成形如下的json文件
> 
> ```
> {
>     "SFT_data": [
>      ["问：xxxxx",
>       "答：xxxxx"]
>     ]
> }
> ```

这里面对话带的"问："和 "答："的符号不用加，记得去掉哈。
