### ISSUE TITLE
与模型交互报错：RuntimeError: cutlassF: no kernel found to launch!

### ISSUE THREAD

**Issue by decaMinCow** [FreedomIntelligence/HuatuoGPT-II#5]
HuatuoGPT: Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 1648, in generate
    return self.sample(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 2730, in sample
    outputs = self(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/autodl-tmp/modules/transformers_modules/HuatuoGPT2-7B/modeling_baichuan.py", line 686, in forward
    outputs = self.model(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/modules/transformers_modules/HuatuoGPT2-7B/modeling_baichuan.py", line 461, in forward
    layer_outputs = decoder_layer(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/autodl-tmp/modules/transformers_modules/HuatuoGPT2-7B/modeling_baichuan.py", line 273, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/autodl-tmp/modules/transformers_modules/HuatuoGPT2-7B/modeling_baichuan.py", line 234, in forward
    attn_output = F.scaled_dot_product_attention(query_states, key_states, value_states, attn_mask = attention_mask)
RuntimeError: cutlassF: no kernel found to launch!

**Comment by decaMinCow** [comment]
请问需要什么样的环境，才能正常运行

**Comment by jymChen** [comment]
Hi @decaMinCow ,
HuatuoGPT2采用了Baichuan2基座，可能需要 torch 2.0以上的环境，环境要求可以看requirements.txt文件。

**Comment by decaMinCow** [comment]
我是 torch 2.0 环境，我是按照 requirements.txt 安装的

**Comment by jymChen** [comment]
可以尝试把xformers卸载下，再运行试试。

**Comment by LiangYong1216** [comment]
> 可以尝试把xformers卸载下，再运行试试。

哈喽，你训练成功了吗？我想使用提供的数据集进行训练，但是当我运行data_process.py时报错。
![image](https://github.com/FreedomIntelligence/HuatuoGPT-II/assets/66230782/361ba11e-3947-4367-bd60-0ed998e9ee56)
数据集长这样：
![image](https://github.com/FreedomIntelligence/HuatuoGPT-II/assets/66230782/b6b255c7-c9af-4f13-afad-76f55de82397)
我应该怎么修改啊，期待您的回复！
